_target_: distribution.WrappedMixture
_convert_: partial

scale     : [[0.15, 0.15, 0.5],[0.15, 0.15, 0.5],[0.15, 0.5, 0.15],[0.15, 0.5, 0.15]]
batch_dims: ${batch_size}
manifold  : ${manifold}
mean_type : hyperboloid4
seed: ${seed}